#!/usr/bin/env python3
"""
Generates include/opcodes.inc (OP_* constants) and src/opcodes_table.s
(the names, interned at startup with their id in the string node's aux).

Ids only matter for the jump tables: every string can be interned at
runtime, with or without an id.
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# Expression opcodes (tuple heads), atoms and other well-known strings.
RENAMES = {"UNKNOWN_OP": "UNKNOWN", "LOOP_UPPER": "LOOP"}

NAMES = """
add mul sub div sdiv mod smod addmod mulmod exp signextend
lt gt slt sgt eq iszero and or xor not byte shl shr sar
sha3 address balance origin caller callvalue calldataload calldatasize
calldatacopy codesize codecopy gasprice extcodesize extcodecopy
returndatasize returndatacopy extcodehash blockhash coinbase timestamp
number difficulty gaslimit chainid selfbalance basefee
pop mload mstore mstore8 sload sstore jump jumpi pc msize gas jumpdest
push push0 dup swap log0 log1 log2 log3 log4 log
create call callcode return delegatecall create2 staticcall revert invalid
selfdestruct stop assert_fail UNKNOWN_OP
le ge sle sge
mask_shl mask neg_mask range mem var cd stor storage if while for goto label
continue setmem setvar setvars store array map loc name field type struct
length bool data arr max min sha3 undefined jd funccall require
call.data call.func_hash ext_call.return_data ext_call.success
delegate.return_data delegate.return_code callcode.return_data
callcode.return_code create.new_address create2.new_address
memcopy.success code.data precompiled param unknown const comment
def set len inputs payable read_only mapping owner fand
x y z sth t a b c LOOP_UPPER push_int merged_if loop
gas_remaining
erecover sha256hash ripemd160hash bigModExp bn256Add bn256ScalarMul bn256Pairing
staticcall.return_data sadd smul
""".split()


def main():
    names = []
    seen = set()
    for n in NAMES:
        if n not in seen:
            seen.add(n)
            names.append(n)

    def cname(n):
        return re.sub(r"[^A-Za-z0-9_]", "_", n).upper()

    consts = [cname(n) for n in names]
    dups = {c for c in consts if consts.count(c) > 1}
    if dups:
        sys.exit(f"opcode constant name collision: {dups}")

    with open(os.path.join(ROOT, "include", "opcodes.inc"), "w") as f:
        f.write("# generated by tools/gen_opcodes.py - do not edit\n")
        for i, n in enumerate(names, 1):
            f.write(f".set OP_{cname(n)}, {i}\n")
        f.write(f".set OP_COUNT, {len(names)}\n")

    with open(os.path.join(ROOT, "src", "opcodes_table.s"), "w") as f:
        f.write("# generated by tools/gen_opcodes.py - do not edit\n")
        f.write('        .section .data.rel.ro\n')
        f.write("        .globl opcode_names, opcode_names_count\n        .hidden opcode_names, opcode_names_count\n")
        f.write("        .align 8\n")
        f.write("opcode_names:\n")
        for i, n in enumerate(names):
            f.write(f'        .quad .Lopname_{i}\n')
        f.write(f"opcode_names_count: .quad {len(names)}\n")
        for i, n in enumerate(names):
            f.write(f'.Lopname_{i}: .asciz "{RENAMES.get(n, n)}"\n')
        # the string node for each opcode, filled at init (for fast access
        # from asm: S_<NAME> is a .quad holding the node pointer)
        f.write("        .section .bss\n        .align 8\n")
        f.write("        .globl opcode_nodes\n        .hidden opcode_nodes\n")
        f.write(f"opcode_nodes: .space {8 * (len(names) + 1)}\n")
        f.write('        .section .note.GNU-stack,"",@progbits\n')


if __name__ == "__main__":
    main()
