# generated by tools/gen_opcodes.py - do not edit
        .section .data.rel.ro
        .globl opcode_names, opcode_names_count
        .hidden opcode_names, opcode_names_count
        .align 8
opcode_names:
        .quad .Lopname_0
        .quad .Lopname_1
        .quad .Lopname_2
        .quad .Lopname_3
        .quad .Lopname_4
        .quad .Lopname_5
        .quad .Lopname_6
        .quad .Lopname_7
        .quad .Lopname_8
        .quad .Lopname_9
        .quad .Lopname_10
        .quad .Lopname_11
        .quad .Lopname_12
        .quad .Lopname_13
        .quad .Lopname_14
        .quad .Lopname_15
        .quad .Lopname_16
        .quad .Lopname_17
        .quad .Lopname_18
        .quad .Lopname_19
        .quad .Lopname_20
        .quad .Lopname_21
        .quad .Lopname_22
        .quad .Lopname_23
        .quad .Lopname_24
        .quad .Lopname_25
        .quad .Lopname_26
        .quad .Lopname_27
        .quad .Lopname_28
        .quad .Lopname_29
        .quad .Lopname_30
        .quad .Lopname_31
        .quad .Lopname_32
        .quad .Lopname_33
        .quad .Lopname_34
        .quad .Lopname_35
        .quad .Lopname_36
        .quad .Lopname_37
        .quad .Lopname_38
        .quad .Lopname_39
        .quad .Lopname_40
        .quad .Lopname_41
        .quad .Lopname_42
        .quad .Lopname_43
        .quad .Lopname_44
        .quad .Lopname_45
        .quad .Lopname_46
        .quad .Lopname_47
        .quad .Lopname_48
        .quad .Lopname_49
        .quad .Lopname_50
        .quad .Lopname_51
        .quad .Lopname_52
        .quad .Lopname_53
        .quad .Lopname_54
        .quad .Lopname_55
        .quad .Lopname_56
        .quad .Lopname_57
        .quad .Lopname_58
        .quad .Lopname_59
        .quad .Lopname_60
        .quad .Lopname_61
        .quad .Lopname_62
        .quad .Lopname_63
        .quad .Lopname_64
        .quad .Lopname_65
        .quad .Lopname_66
        .quad .Lopname_67
        .quad .Lopname_68
        .quad .Lopname_69
        .quad .Lopname_70
        .quad .Lopname_71
        .quad .Lopname_72
        .quad .Lopname_73
        .quad .Lopname_74
        .quad .Lopname_75
        .quad .Lopname_76
        .quad .Lopname_77
        .quad .Lopname_78
        .quad .Lopname_79
        .quad .Lopname_80
        .quad .Lopname_81
        .quad .Lopname_82
        .quad .Lopname_83
        .quad .Lopname_84
        .quad .Lopname_85
        .quad .Lopname_86
        .quad .Lopname_87
        .quad .Lopname_88
        .quad .Lopname_89
        .quad .Lopname_90
        .quad .Lopname_91
        .quad .Lopname_92
        .quad .Lopname_93
        .quad .Lopname_94
        .quad .Lopname_95
        .quad .Lopname_96
        .quad .Lopname_97
        .quad .Lopname_98
        .quad .Lopname_99
        .quad .Lopname_100
        .quad .Lopname_101
        .quad .Lopname_102
        .quad .Lopname_103
        .quad .Lopname_104
        .quad .Lopname_105
        .quad .Lopname_106
        .quad .Lopname_107
        .quad .Lopname_108
        .quad .Lopname_109
        .quad .Lopname_110
        .quad .Lopname_111
        .quad .Lopname_112
        .quad .Lopname_113
        .quad .Lopname_114
        .quad .Lopname_115
        .quad .Lopname_116
        .quad .Lopname_117
        .quad .Lopname_118
        .quad .Lopname_119
        .quad .Lopname_120
        .quad .Lopname_121
        .quad .Lopname_122
        .quad .Lopname_123
        .quad .Lopname_124
        .quad .Lopname_125
        .quad .Lopname_126
        .quad .Lopname_127
        .quad .Lopname_128
        .quad .Lopname_129
        .quad .Lopname_130
        .quad .Lopname_131
        .quad .Lopname_132
        .quad .Lopname_133
        .quad .Lopname_134
        .quad .Lopname_135
        .quad .Lopname_136
        .quad .Lopname_137
        .quad .Lopname_138
        .quad .Lopname_139
        .quad .Lopname_140
        .quad .Lopname_141
        .quad .Lopname_142
        .quad .Lopname_143
        .quad .Lopname_144
        .quad .Lopname_145
        .quad .Lopname_146
        .quad .Lopname_147
        .quad .Lopname_148
        .quad .Lopname_149
        .quad .Lopname_150
        .quad .Lopname_151
        .quad .Lopname_152
        .quad .Lopname_153
        .quad .Lopname_154
        .quad .Lopname_155
        .quad .Lopname_156
        .quad .Lopname_157
        .quad .Lopname_158
        .quad .Lopname_159
        .quad .Lopname_160
        .quad .Lopname_161
        .quad .Lopname_162
        .quad .Lopname_163
        .quad .Lopname_164
        .quad .Lopname_165
        .quad .Lopname_166
        .quad .Lopname_167
        .quad .Lopname_168
        .quad .Lopname_169
        .quad .Lopname_170
        .quad .Lopname_171
        .quad .Lopname_172
        .quad .Lopname_173
        .quad .Lopname_174
        .quad .Lopname_175
        .quad .Lopname_176
        .quad .Lopname_177
        .quad .Lopname_178
        .quad .Lopname_179
        .quad .Lopname_180
        .quad .Lopname_181
        .quad .Lopname_182
        .quad .Lopname_183
        .quad .Lopname_184
        .quad .Lopname_185
opcode_names_count: .quad 186
.Lopname_0: .asciz "add"
.Lopname_1: .asciz "mul"
.Lopname_2: .asciz "sub"
.Lopname_3: .asciz "div"
.Lopname_4: .asciz "sdiv"
.Lopname_5: .asciz "mod"
.Lopname_6: .asciz "smod"
.Lopname_7: .asciz "addmod"
.Lopname_8: .asciz "mulmod"
.Lopname_9: .asciz "exp"
.Lopname_10: .asciz "signextend"
.Lopname_11: .asciz "lt"
.Lopname_12: .asciz "gt"
.Lopname_13: .asciz "slt"
.Lopname_14: .asciz "sgt"
.Lopname_15: .asciz "eq"
.Lopname_16: .asciz "iszero"
.Lopname_17: .asciz "and"
.Lopname_18: .asciz "or"
.Lopname_19: .asciz "xor"
.Lopname_20: .asciz "not"
.Lopname_21: .asciz "byte"
.Lopname_22: .asciz "shl"
.Lopname_23: .asciz "shr"
.Lopname_24: .asciz "sar"
.Lopname_25: .asciz "sha3"
.Lopname_26: .asciz "address"
.Lopname_27: .asciz "balance"
.Lopname_28: .asciz "origin"
.Lopname_29: .asciz "caller"
.Lopname_30: .asciz "callvalue"
.Lopname_31: .asciz "calldataload"
.Lopname_32: .asciz "calldatasize"
.Lopname_33: .asciz "calldatacopy"
.Lopname_34: .asciz "codesize"
.Lopname_35: .asciz "codecopy"
.Lopname_36: .asciz "gasprice"
.Lopname_37: .asciz "extcodesize"
.Lopname_38: .asciz "extcodecopy"
.Lopname_39: .asciz "returndatasize"
.Lopname_40: .asciz "returndatacopy"
.Lopname_41: .asciz "extcodehash"
.Lopname_42: .asciz "blockhash"
.Lopname_43: .asciz "coinbase"
.Lopname_44: .asciz "timestamp"
.Lopname_45: .asciz "number"
.Lopname_46: .asciz "difficulty"
.Lopname_47: .asciz "gaslimit"
.Lopname_48: .asciz "chainid"
.Lopname_49: .asciz "selfbalance"
.Lopname_50: .asciz "basefee"
.Lopname_51: .asciz "pop"
.Lopname_52: .asciz "mload"
.Lopname_53: .asciz "mstore"
.Lopname_54: .asciz "mstore8"
.Lopname_55: .asciz "sload"
.Lopname_56: .asciz "sstore"
.Lopname_57: .asciz "jump"
.Lopname_58: .asciz "jumpi"
.Lopname_59: .asciz "pc"
.Lopname_60: .asciz "msize"
.Lopname_61: .asciz "gas"
.Lopname_62: .asciz "jumpdest"
.Lopname_63: .asciz "push"
.Lopname_64: .asciz "push0"
.Lopname_65: .asciz "dup"
.Lopname_66: .asciz "swap"
.Lopname_67: .asciz "log0"
.Lopname_68: .asciz "log1"
.Lopname_69: .asciz "log2"
.Lopname_70: .asciz "log3"
.Lopname_71: .asciz "log4"
.Lopname_72: .asciz "log"
.Lopname_73: .asciz "create"
.Lopname_74: .asciz "call"
.Lopname_75: .asciz "callcode"
.Lopname_76: .asciz "return"
.Lopname_77: .asciz "delegatecall"
.Lopname_78: .asciz "create2"
.Lopname_79: .asciz "staticcall"
.Lopname_80: .asciz "revert"
.Lopname_81: .asciz "invalid"
.Lopname_82: .asciz "selfdestruct"
.Lopname_83: .asciz "stop"
.Lopname_84: .asciz "assert_fail"
.Lopname_85: .asciz "UNKNOWN"
.Lopname_86: .asciz "le"
.Lopname_87: .asciz "ge"
.Lopname_88: .asciz "sle"
.Lopname_89: .asciz "sge"
.Lopname_90: .asciz "mask_shl"
.Lopname_91: .asciz "mask"
.Lopname_92: .asciz "neg_mask"
.Lopname_93: .asciz "range"
.Lopname_94: .asciz "mem"
.Lopname_95: .asciz "var"
.Lopname_96: .asciz "cd"
.Lopname_97: .asciz "stor"
.Lopname_98: .asciz "storage"
.Lopname_99: .asciz "if"
.Lopname_100: .asciz "while"
.Lopname_101: .asciz "for"
.Lopname_102: .asciz "goto"
.Lopname_103: .asciz "label"
.Lopname_104: .asciz "continue"
.Lopname_105: .asciz "setmem"
.Lopname_106: .asciz "setvar"
.Lopname_107: .asciz "setvars"
.Lopname_108: .asciz "store"
.Lopname_109: .asciz "array"
.Lopname_110: .asciz "map"
.Lopname_111: .asciz "loc"
.Lopname_112: .asciz "name"
.Lopname_113: .asciz "field"
.Lopname_114: .asciz "type"
.Lopname_115: .asciz "struct"
.Lopname_116: .asciz "length"
.Lopname_117: .asciz "bool"
.Lopname_118: .asciz "data"
.Lopname_119: .asciz "arr"
.Lopname_120: .asciz "max"
.Lopname_121: .asciz "min"
.Lopname_122: .asciz "undefined"
.Lopname_123: .asciz "jd"
.Lopname_124: .asciz "funccall"
.Lopname_125: .asciz "require"
.Lopname_126: .asciz "call.data"
.Lopname_127: .asciz "call.func_hash"
.Lopname_128: .asciz "ext_call.return_data"
.Lopname_129: .asciz "ext_call.success"
.Lopname_130: .asciz "delegate.return_data"
.Lopname_131: .asciz "delegate.return_code"
.Lopname_132: .asciz "callcode.return_data"
.Lopname_133: .asciz "callcode.return_code"
.Lopname_134: .asciz "create.new_address"
.Lopname_135: .asciz "create2.new_address"
.Lopname_136: .asciz "memcopy.success"
.Lopname_137: .asciz "code.data"
.Lopname_138: .asciz "precompiled"
.Lopname_139: .asciz "param"
.Lopname_140: .asciz "unknown"
.Lopname_141: .asciz "const"
.Lopname_142: .asciz "comment"
.Lopname_143: .asciz "def"
.Lopname_144: .asciz "set"
.Lopname_145: .asciz "len"
.Lopname_146: .asciz "inputs"
.Lopname_147: .asciz "payable"
.Lopname_148: .asciz "read_only"
.Lopname_149: .asciz "mapping"
.Lopname_150: .asciz "owner"
.Lopname_151: .asciz "fand"
.Lopname_152: .asciz "x"
.Lopname_153: .asciz "y"
.Lopname_154: .asciz "z"
.Lopname_155: .asciz "sth"
.Lopname_156: .asciz "t"
.Lopname_157: .asciz "a"
.Lopname_158: .asciz "b"
.Lopname_159: .asciz "c"
.Lopname_160: .asciz "LOOP"
.Lopname_161: .asciz "push_int"
.Lopname_162: .asciz "merged_if"
.Lopname_163: .asciz "loop"
.Lopname_164: .asciz "gas_remaining"
.Lopname_165: .asciz "erecover"
.Lopname_166: .asciz "sha256hash"
.Lopname_167: .asciz "ripemd160hash"
.Lopname_168: .asciz "bigModExp"
.Lopname_169: .asciz "bn256Add"
.Lopname_170: .asciz "bn256ScalarMul"
.Lopname_171: .asciz "bn256Pairing"
.Lopname_172: .asciz "staticcall.return_data"
.Lopname_173: .asciz "sadd"
.Lopname_174: .asciz "smul"
.Lopname_175: .asciz "cleared"
.Lopname_176: .asciz "bytes"
.Lopname_177: .asciz "sbytes"
.Lopname_178: .asciz "tload"
.Lopname_179: .asciz "tstore"
.Lopname_180: .asciz "mcopy"
.Lopname_181: .asciz "blobhash"
.Lopname_182: .asciz "blobbasefee"
.Lopname_183: .asciz "codecall"
.Lopname_184: .asciz "land"
.Lopname_185: .asciz "lor"
        .section .bss
        .align 8
        .globl opcode_nodes
        .hidden opcode_nodes
opcode_nodes: .space 1496
        .section .note.GNU-stack,"",@progbits
